### ISSUE TITLE
Feature Requestion: Model Specification

### ISSUE THREAD

**Issue by yijunwang0805** [lilywang1988/eSIR#32]
Hi,

Thank you for your great package!

Could you extend the flexibility of the package so that is is possible for users to define their own epi model such as SEIR, SEIRD, etc?

Best regards,
Yijun

**Comment by lilywang1988** [comment]
Hi Yijun,

They are non-trivial extensions! People in Song Lab will continue working on them. Thank you for your suggestions.

Best,
Lili
